Repository nttcom/moq-wasm, pull requests merged in 2024-10, with the labels that each got.

#97 Added Object messages
  moqt-core/src/modules/messages.rs
  moqt-core/src/modules/messages/control_messages.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/announce_error.rs
  moqt-core/src/modules/messages/control_messages/announce_ok.rs
  moqt-core/src/modules/messages/control_messages/client_setup.rs
  moqt-core/src/modules/messages/control_messages/go_away.rs
  moqt-core/src/modules/messages/control_messages/server_setup.rs
  moqt-core/src/modules/messages/control_messages/setup_parameters.rs
  moqt-core/src/modules/messages/control_messages/subscribe.rs
  moqt-core/src/modules/messages/control_messages/subscribe_error.rs
  moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
  moqt-core/src/modules/messages/control_messages/unannounce.rs
  moqt-core/src/modules/messages/control_messages/unsubscribe.rs
  moqt-core/src/modules/messages/control_messages/version_specific_parameters.rs
  moqt-core/src/modules/messages/data_streams.rs
  moqt-core/src/modules/messages/data_streams/object_datagram.rs
  moqt-core/src/modules/messages/data_streams/object_status.rs
  moqt-core/src/modules/messages/data_streams/object_stream_subgroup.rs
  moqt-core/src/modules/messages/data_streams/object_stream_track.rs
  moqt-core/src/modules/messages/data_streams/stream_header_subgroup.rs
  moqt-core/src/modules/messages/data_streams/stream_header_track.rs
  moqt-core/src/modules/messages/object.rs
  moqt-core/src/modules/moqt_client.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers.rs
  moqt-server/src/modules/handlers/announce_handler.rs
  moqt-server/src/modules/handlers/object_handler.rs
  moqt-server/src/modules/handlers/server_setup_handler.rs
  moqt-server/src/modules/handlers/subscribe_handler.rs
  moqt-server/src/modules/handlers/subscribe_ok_handler.rs
  moqt-server/src/modules/handlers/unannounce_handler.rs
  moqt-server/src/modules/handlers/unsubscribe_handler.rs
  moqt-server/src/modules/server_processes.rs
  moqt-server/src/modules/server_processes/announce_message.rs
  moqt-server/src/modules/server_processes/client_setup_message.rs
  moqt-server/src/modules/server_processes/object_message.rs
  moqt-server/src/modules/server_processes/subscribe_message.rs
  moqt-server/src/modules/server_processes/subscribe_ok_message.rs
Labels: implementation, draft-06

#98 Update setup parameter along 06
  js/index.html
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/client_setup.rs
  moqt-core/src/modules/messages/control_messages/server_setup.rs
  moqt-core/src/modules/messages/control_messages/setup_parameters.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers/server_setup_handler.rs
Labels: implementation, draft-06

#99 Use N-tuple in TrackNameSpace
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/announce_error.rs
  moqt-core/src/modules/messages/control_messages/announce_ok.rs
  moqt-core/src/modules/messages/control_messages/subscribe.rs
  moqt-core/src/modules/messages/control_messages/subscribe_error.rs
  moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
  moqt-core/src/modules/messages/control_messages/unannounce.rs
  moqt-core/src/modules/messages/control_messages/unsubscribe.rs
  moqt-core/src/modules/track_namespace_manager_repository.rs
  moqt-server/src/modules/handlers/announce_handler.rs
  moqt-server/src/modules/handlers/subscribe_handler.rs
  moqt-server/src/modules/handlers/subscribe_ok_handler.rs
  moqt-server/src/modules/handlers/unannounce_handler.rs
  moqt-server/src/modules/track_namespace_manager.rs
Labels: implementation, draft-06

#102 Update Subscribe OK message along 06
  moqt-core/src/modules/messages/control_messages/subscribe.rs
  moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
  moqt-core/src/modules/messages/data_streams/object_datagram.rs
  moqt-core/src/modules/messages/data_streams/object_stream_subgroup.rs
  moqt-core/src/modules/messages/data_streams/object_stream_track.rs
  moqt-server/src/modules/handlers/subscribe_ok_handler.rs
Labels: implementation, draft-06

#106 Packetize Payload Type as x(b)
  moqt-client-sample/src/lib.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/control_message_handler.rs
Labels: refactoring, implementation, draft-06

#107 Manage Subscribe ID and Track Alias on client side
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/models/subscriptions.rs
Labels: implementation, draft-06

#109 Support Subscribe ID and Track Alias
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/lib.rs
  moqt-core/src/modules.rs
  moqt-core/src/modules/messages/control_messages/subscribe.rs
  moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
  moqt-core/src/modules/messages/data_streams/object_datagram.rs
  moqt-core/src/modules/messages/data_streams/object_stream_subgroup.rs
  moqt-core/src/modules/messages/data_streams/object_stream_track.rs
  moqt-core/src/modules/models.rs
  moqt-core/src/modules/models/subscriptions.rs
  moqt-core/src/modules/models/subscriptions/nodes.rs
  moqt-core/src/modules/models/subscriptions/nodes/consumers.rs
  moqt-core/src/modules/models/subscriptions/nodes/producers.rs
  moqt-core/src/modules/models/subscriptions/nodes/registry.rs
  moqt-core/src/modules/models/tracks.rs
  moqt-core/src/modules/pubsub_relation_manager_repository.rs
  moqt-core/src/modules/track_namespace_manager_repository.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers/announce_handler.rs
  moqt-server/src/modules/handlers/server_setup_handler.rs
  moqt-server/src/modules/handlers/subscribe_handler.rs
  moqt-server/src/modules/handlers/subscribe_ok_handler.rs
  moqt-server/src/modules/handlers/unannounce_handler.rs
  moqt-server/src/modules/handlers/unsubscribe_handler.rs
  moqt-server/src/modules/pubsub_relation_manager.rs
  moqt-server/src/modules/pubsub_relation_manager/commands.rs
  moqt-server/src/modules/pubsub_relation_manager/manager.rs
  moqt-server/src/modules/pubsub_relation_manager/relation.rs
  moqt-server/src/modules/pubsub_relation_manager/wrapper.rs
  moqt-server/src/modules/server_processes/announce_message.rs
  moqt-server/src/modules/server_processes/client_setup_message.rs
  moqt-server/src/modules/server_processes/subscribe_message.rs
  moqt-server/src/modules/server_processes/subscribe_ok_message.rs
  moqt-server/src/modules/track_namespace_manager.rs
Labels: draft-06

#112 Update MoQ Transport version to 06
  README.md
  interoperability_test.md
  js/index.html
  moqt-core/src/modules/constants.rs
  moqt-core/src/modules/messages/control_messages/client_setup.rs
  moqt-core/src/modules/messages/control_messages/server_setup.rs
  moqt-server/src/modules/control_message_handler.rs
Labels: implementation, draft-06

#110 Implementd object cache storage and relay functions for track stream
  Cargo.lock
  moqt-core/src/modules.rs
  moqt-core/src/modules/data_stream_type.rs
  moqt-core/src/modules/messages/data_streams.rs
  moqt-core/src/modules/messages/data_streams/object_datagram.rs
  moqt-core/src/modules/messages/data_streams/object_stream_subgroup.rs
  moqt-core/src/modules/messages/data_streams/object_stream_track.rs
  moqt-core/src/modules/messages/data_streams/stream_header_subgroup.rs
  moqt-core/src/modules/messages/data_streams/stream_header_track.rs
  moqt-core/src/modules/models/subscriptions.rs
  moqt-core/src/modules/models/subscriptions/nodes/consumers.rs
  moqt-core/src/modules/models/subscriptions/nodes/producers.rs
  moqt-core/src/modules/models/subscriptions/nodes/registry.rs
  moqt-core/src/modules/models/tracks.rs
  moqt-core/src/modules/pubsub_relation_manager_repository.rs
  moqt-core/src/modules/variable_bytes.rs
  moqt-server/Cargo.toml
  moqt-server/src/lib.rs
  moqt-server/src/modules.rs
  moqt-server/src/modules/handlers.rs
  moqt-server/src/modules/handlers/stream_track_header_handler.rs
  moqt-server/src/modules/object_cache_storage.rs
  moqt-server/src/modules/object_stream_handler.rs
  moqt-server/src/modules/pubsub_relation_manager/commands.rs
  moqt-server/src/modules/pubsub_relation_manager/manager.rs
  moqt-server/src/modules/pubsub_relation_manager/relation.rs
  moqt-server/src/modules/pubsub_relation_manager/wrapper.rs
  moqt-server/src/modules/server_processes.rs
  moqt-server/src/modules/server_processes/stream_track_header.rs
  moqt-server/src/modules/stream_header_handler.rs
Labels: implementation, draft-06

#111 Implemented client functions for track stream and fixed relay
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/handlers/subscribe_handler.rs
Labels: implementation, draft-06

#121 Support client send/recv SUBSCRIBE_NAMESPACE
  README.md
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace_ok.rs
Labels: implementation, draft-06

#120 Support new messages relay feature
  README.md
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace_ok.rs
  moqt-server/src/lib.rs
Labels: implementation, draft-06

#117 Propagate announce if the namespace was subscribed by subscribers
  README.md
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/announce_error.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace_ok.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers/announce_handler.rs
  moqt-server/src/modules/handlers/subscribe_namespace_handler.rs
  moqt-server/src/modules/pubsub_relation_manager/manager.rs
  moqt-server/src/modules/server_processes/announce_message.rs
Labels: implementation, draft-06, fix_later

#119 Changed the method to create relay messages
  moqt-core/src/modules/messages/control_messages/subscribe.rs
  moqt-core/src/modules/messages/control_messages/subscribe_error.rs
  moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
  moqt-core/src/modules/messages/data_streams/stream_header_track.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/handlers/subscribe_error_handler.rs
  moqt-server/src/modules/handlers/subscribe_handler.rs
  moqt-server/src/modules/handlers/subscribe_ok_handler.rs
Labels: refactoring

#116 Support ANNOUNCE_OK and ANNOUNCE_ERROR handler
  README.md
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/announce_error.rs
  moqt-core/src/modules/messages/control_messages/announce_ok.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace_ok.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers.rs
  moqt-server/src/modules/handlers/announce_handler.rs
  moqt-server/src/modules/handlers/announce_ok_handler.rs
  moqt-server/src/modules/handlers/subscribe_namespace_handler.rs
  moqt-server/src/modules/pubsub_relation_manager/manager.rs
  moqt-server/src/modules/server_processes.rs
  moqt-server/src/modules/server_processes/announce_error_message.rs
  moqt-server/src/modules/server_processes/announce_message.rs
  moqt-server/src/modules/server_processes/announce_ok_message.rs
Labels: implementation, draft-06

#122 Fixed client freeze issue
  js/main.js
  moqt-client-sample/src/lib.rs
Labels: refactoring, improvement

#113 Support SUBSCRIBE_ERROR handler
  README.md
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/subscribe.rs
  moqt-core/src/modules/messages/control_messages/subscribe_error.rs
  moqt-core/src/modules/messages/control_messages/subscribe_ok.rs
  moqt-core/src/modules/messages/data_streams/stream_header_track.rs
  moqt-core/src/modules/models/subscriptions/nodes/consumers.rs
  moqt-core/src/modules/models/subscriptions/nodes/producers.rs
  moqt-core/src/modules/models/subscriptions/nodes/registry.rs
  moqt-core/src/modules/pubsub_relation_manager_repository.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers.rs
  moqt-server/src/modules/handlers/subscribe_error_handler.rs
  moqt-server/src/modules/handlers/subscribe_handler.rs
  moqt-server/src/modules/handlers/subscribe_ok_handler.rs
  moqt-server/src/modules/pubsub_relation_manager/commands.rs
  moqt-server/src/modules/pubsub_relation_manager/manager.rs
  moqt-server/src/modules/pubsub_relation_manager/relation.rs
  moqt-server/src/modules/pubsub_relation_manager/wrapper.rs
  moqt-server/src/modules/server_processes.rs
  moqt-server/src/modules/server_processes/subscribe_error_message.rs
  moqt-server/src/modules/server_processes/subscribe_message.rs
Labels: implementation, draft-06

#115 Add SUBSCRIBE_NAMESPACE handler
  README.md
  js/index.html
  js/main.js
  moqt-client-sample/src/lib.rs
  moqt-core/src/modules/messages/control_messages/announce.rs
  moqt-core/src/modules/messages/control_messages/announce_error.rs
  moqt-core/src/modules/messages/control_messages/announce_ok.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace_error.rs
  moqt-core/src/modules/messages/control_messages/subscribe_namespace_ok.rs
  moqt-core/src/modules/models/subscriptions/nodes/producers.rs
  moqt-core/src/modules/pubsub_relation_manager_repository.rs
  moqt-server/src/lib.rs
  moqt-server/src/modules/control_message_handler.rs
  moqt-server/src/modules/handlers.rs
  moqt-server/src/modules/handlers/announce_handler.rs
  moqt-server/src/modules/handlers/announce_ok_handler.rs
  moqt-server/src/modules/handlers/subscribe_namespace_handler.rs
  moqt-server/src/modules/pubsub_relation_manager/commands.rs
  moqt-server/src/modules/pubsub_relation_manager/manager.rs
  moqt-server/src/modules/pubsub_relation_manager/wrapper.rs
  moqt-server/src/modules/server_processes.rs
  moqt-server/src/modules/server_processes/announce_error_message.rs
  moqt-server/src/modules/server_processes/announce_message.rs
  moqt-server/src/modules/server_processes/announce_ok_message.rs
  moqt-server/src/modules/server_processes/subscribe_namespace_message.rs
Labels: implementation, draft-06, fix_later
